apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jdui6g0qr-java-springboot
  janus-idp.io/tekton: jdui6g0qr-java-springboot
  backstage.io/kubernetes-id: jdui6g0qr-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jdui6g0qr-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
